sudo: false
language: ruby
rvm:
  - 2.4.1
before_install: 
  - gem install bundler -v 1.14.6
  - gem install sym
  - sym -k SAVES_CLIENT_ENCRYPTION_KEY -n vendor/saves_client-3.2.1.gem.enc
  - gem install -f vendor/saves_client*.gem

