#!/usr/bin/env ruby -W0

lib_path = File.dirname(__FILE__) + '/../lib'
if File.exist?(lib_path)
  $LOAD_PATH << lib_path
end

require 'saves/cli'
require 'saves/cli/client'

Saves::CLI::App.new(ARGV).parse!.run!
